sudo: false
language: rust
cache: cargo

# run builds for all the trains (and more)
rust:
  - stable
  - nightly
  - 1.12.0
  - 1.13.0
  - beta

matrix:
  include:
    - rust: nightly
      env: CLIPPY=true

script: ./travis.sh
