sudo: false
language: rust
cache: cargo

# run builds for all the trains (and more)
rust:
  - stable
  - nightly
  - 1.12.0
  - 1.13.0
  - beta

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

script:
  - (cd json && travis-cargo build)
  - (cd json && travis-cargo build -- --features preserve_order)
  - (cd json && travis-cargo --only nightly test)
  - (cd json_tests && travis-cargo --only beta test)
  - (cd json_tests && travis-cargo --only nightly test -- --features unstable-testing)

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
