[package]
name = "eager_json"
version = "0.1.0" # remember to update html_root_url
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Deserialize JSON from io::Read by buffering into a string"
repository = "https://github.com/serde-rs/json/tree/eager"
documentation = "https://docs.rs/eager_json"
categories = ["encoding"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
