[package]
name = "serde_json_tests"
version = "0.0.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
publish = false

[features]
trace-macros = []

[dependencies]
serde = "0.9"
serde_json = { path = "../json" }
serde_derive = "0.9"

[[test]]
name = "test"
path = "tests/test.rs"
