[package]
name = "serde_json_tests"
version = "0.6.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_macros"]
with-syntex = ["syntex", "serde_codegen"]

[build-dependencies]
syntex = { version = "*", optional = true }
serde_codegen = { version = "^0.6.0", optional = true }

[dependencies]
num = "^0.1.27"
rustc-serialize = "0.3.18"
serde = "^0.6.0"
serde_json = { version = "*", path = "../json" }
serde_macros = { version = "^0.6.0", optional = true }

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
