[package]
name = "serde_json_tests"
version = "0.9.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
publish = false

[features]
unstable-testing = ["clippy", "serde_json/clippy"]
trace-macros = []

[dependencies]
clippy = { version = "0.*", optional = true }
num-traits = "*"
rustc-serialize = "*"
serde = "0.9"
serde_json = { path = "../json" }
serde_derive = "0.9"

[[test]]
name = "test"
path = "tests/test.rs"
